apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gc-gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: ep-envoy-proxy
    namespace: envoy-gateway-system
